version: '3'

services:
  bitcoin-node:
    build: .
    image: xorde/bitcoin-node
    restart: unless-stopped
    volumes:
      - bitcoin_data:/root/.bitcoin
    environment:
      - WALLET_ENABLE
      - TESTNET
      - MAX_CONNECTIONS
      - ONLYNET
      - RPC_SERVER
      - RPC_USER
      - RPC_PASSWORD
    ports:
      - ${NODE_PORT}:8332/tcp
      - ${NODE_RPC_PORT}:8333/tcp

volumes:
  bitcoin_data:
    driver: local
