version: '3.4'

services:
  bitcoin-node:
    build:
      context: .
      network: host
    image: ghcr.io/xorde-nodes/bitcoin-node:latest
    restart: unless-stopped
    volumes:
      - bitcoin_data:/home/bitcoin/.bitcoin
    environment:
      - WALLET_ENABLE
      - TESTNET_ENABLE
      - MAX_CONNECTIONS
      - RPC_ENABLE
      - RPC_USER
      - RPC_PASSWORD
      - RPC_ALLOW
      - RPC_PORT
      - RPC_BIND
      - CONFIG_FILE
      - SOCKS5_PROXY
      - TXINDEX_ENABLE
    ports:
      - ${RPC_PORT}:8332/tcp
      - ${PORT}:8333/tcp

volumes:
  bitcoin_data:
    driver: local
