version: '3'

services:
  bitcoin-node:
    build: .
    restart: unless-stopped
    volumes:
      - node_data:/root/.bitcoin
    environment:
      - WALLET_ENABLE=${WALLET_ENABLE}
      - TESTNET=${TESTNET}
      - MAX_CONNECTIONS=${MAX_CONNECTIONS}
      - ONLYNET=${ONLYNET}
      - RPC_SERVER=${RPC_SERVER}
      - RPC_USER=${RPC_USER}
      - RPC_PASSWORD=${RPC_PASSWORD}
    ports:
      - ${NODE_PORT}:8332/tcp
      - ${NODE_RPC_PORT}:8333/tcp

volumes:
  bitcoin_data:
    driver: local
