name: Docker Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '1 1 1 * *'

jobs:
  build:
    strategy:
      matrix:
        platforms:
          - linux/arm64
          - linux/amd64
          - linux/arm/v7
          - linux/arm/v6
          - linux/ppc64le
          - linux/s390x

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

      # Workaround: https://github.com/docker/build-push-action/issues/461
    - name: Setup Docker buildx
      uses: docker/setup-buildx-action@v2
      with:
        platforms: ${{ matrix.platforms }}

    # Build and push Docker image with Buildx (don't push on PR)
    # https://github.com/docker/build-push-action
    - name: Build and push Docker image
      id: build-and-push
      uses: docker/build-push-action@v3
      with:
        context: .
        push: false
        tags: ${{ steps.meta.outputs.tags }}
        platforms: ${{ matrix.platforms }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: |
          DOCKER_GIT_SHA=${{ github.sha }}
