name: Docker Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '1 1 1 * *'

env:
  DOCKER_PLATFORMS: ${{ vars.DOCKER_PLATFORMS || 'linux/s390x, linux/ppc64le, linux/arm64, linux/arm/v7, linux/arm/v6, linux/amd64, linux/s390x' }}

jobs:
  matrix:
    runs-on: ubuntu-latest
    outputs:
      platforms: ${{ steps.platforms_matrix.outputs.platforms }}
    steps:
      - name: Platforms matrix
        id: platforms_matrix
        run: |
          echo "platforms=$(echo '${{ env.DOCKER_PLATFORMS }}' | tr -d ' ' | tr ',' '\n' | jq -R . | jq -sc .)" >> $GITHUB_OUTPUT
      - name: Print platforms
        run: |
          echo ${{ steps.platforms_matrix.outputs.platforms }}

  build:
    needs: matrix

    strategy:
      matrix:
        platforms: ${{ needs.matrix.outputs.platforms }}

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

      # Workaround: https://github.com/docker/build-push-action/issues/461
    - name: Setup Docker buildx
      uses: docker/setup-buildx-action@v2
      with:
        platforms: ${{ matrix.platforms }}

    # Build and push Docker image with Buildx (don't push on PR)
    # https://github.com/docker/build-push-action
    - name: Build and push Docker image
      id: build-and-push
      uses: docker/build-push-action@v3
      with:
        context: .
        push: false
        tags: ${{ steps.meta.outputs.tags }}
        platforms: ${{ matrix.platforms }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: |
          DOCKER_GIT_SHA=${{ github.sha }}
